import networkx as nx
import matplotlib.pyplot as plt
G=nx.Graph()
f = open("input.txt", "r")
f.readline()
for x in f:
    edge = x.split(" ")
    G.add_edge(int(edge[0]),int(edge[1]),weight=edge[2])
f.close()
a = list(G.nodes)
# print(a)
# print(G.nodes.data())
pos=nx.spring_layout(G)
labels = nx.get_edge_attributes(G,'weight')
nx.draw_networkx_edge_labels(G,pos,edge_labels=labels)
#nx.draw_networkx_nodes(G,pos)
nx.draw(G,pos,node_color="blue", node_size=300, cmap=plt.cm.Blues, with_labels=True, font_weight='bold', font_color = 'red')
#nx.draw(G, with_labels=True, font_weight='bold')
#plt.savefig("path_graph1.png")
plt.show()